name: Test Push to main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Set up bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies ⏬
      run: bun install

    - name: Lint code 💄
      run: bun run lint

    - name: Typecheck code 🤖
      run: bun run typecheck

    - name: Test code ✅
      run: bun run test

    - name: Build artifacts 🏗️
      run: bun run build

    - name: Publish to coveralls ⭐
      # coverage/lcov.info was generated in the previous npm run build step
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
